IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Candidate')
BEGIN
	CREATE TABLE [Candidates].[dbo].[Candidate] (
		[Id] [bigint] IDENTITY NOT NULL,
		[FirstName] [nvarchar](max) NOT NULL,
		[Street] [nvarchar](max) NULL,
		[PostalCode] [nvarchar](max) NULL,
	 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END